---
   - name: Include app vars
     include_vars:
       file: base_vars.yaml
       #       name: appname
       
   - name : Install base packages
     yum: name={{item}} state=latest
     with_items:
       - httpd
       - epel-release
       - python2-pip
       - vim
       - bash-completion
   - notify:
     systemd: name={{item}}  state=restarted enabled=yes
     with_items:
       - httpd
       - firewalld
    
   - name: Create Webapp Directory Structure
     file: path=/var/www/{{app_name}} state=directory

   - name: Create cgi-bin dir
     file: path=/var/www/{{app_name}}/cgi-bin state=directory
