---
   - name: Include app vars
     include_vars:
       file: base_vars.yaml
       #       name: appname
       
   - name : Install base packages
     yum: name={{item}} state=latest
     with_items:
       - httpd
       - tree
       - python34-pip
       - mariadb
       - mongodb
       - wget
       - elinks
       - epel-release
       - python2-pip
       - vim
       - bash-completion
   - notify:
     systemd: name={{item}}  state=restarted enabled=yes
     with_items:
       - httpd
       - firewalld
       - mariadb
       - mongodb
    
   - name: Create Webapp Directory Structure
     file: path=/var/www/html/{{app_name}} state=directory

   - name: Create cgi-bin dir
     file: path=/var/www/html/{{app_name}}/cgi-bin state=directory
